language: java
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - oracle-java9-installer

jdk: oraclejdk9

install:
# Download pro and build it...
- wget --no-check-certificate https://github.com/forax/pro/archive/master.zip
- unzip master.zip
- cd pro-master
- chmod u+x build.sh
- ./build.sh
- cd ..

script:
- ./pro-master/target/pro/bin/pro

